# Generated by Django 2.1.4 on 2018-12-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kick_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kickstarter',
            options={'ordering': ['backers_count']},
        ),
    ]
