# Generated by Django 2.1.4 on 2018-12-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kickstartercampaign',
            name='created_at',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kickstartercampaign',
            name='deadline',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kickstartercampaign',
            name='disable_communication',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kickstartercampaign',
            name='is_starrable',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kickstartercampaign',
            name='launched_at',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kickstartercampaign',
            name='spotlight',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kickstartercampaign',
            name='staff_pick',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kickstartercampaign',
            name='state_changed_at',
            field=models.IntegerField(),
        ),
    ]
