# Generated by Django 2.1.4 on 2018-12-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nasacomments',
            old_name='imageURL',
            new_name='image_url',
        ),
    ]
