# Generated by Django 2.1.4 on 2018-12-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasa_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nasacomment',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='nasacomment',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='nasacomment',
            old_name='Rating',
            new_name='rating',
        ),
    ]
